### PR TITLE
When generating the code, merge the module-related packages into the package.json file

### LINKED ISSUE #1130: [BUG] Generated codes does not include the necessary dependency packages related to modules
## Describe the bug
Despite selecting the GraphQL module in the CLI, the generated code does not include the necessary GraphQL-related package `graphql-request`.

## To Reproduce
1. `npx create-codes`
1. Generate the code with the following cli options.
1. Complete the setup.
1. Check the `package.json` file in the generated code.
1. `graphql-request` is not installed

### CLI Options

```sh
? Where Would You like to Create Your Application? ./my-app
? Select a JavsScript library for UI React
? Select an API Solution GraphQL
? Select module do you want to use Add CRUD Operations
? Add Testing codes for Catching bugs early? No
```

## Expected behavior
`graphql-request` is located in `dependencies`.

## Related packages/templates
`create-codes`

### PR DESCRIPTION
**Pull request by jinmayamashita**
fix #1130

## What I did

I added the process of merging module-related packages when generating the code in `create-codes`, as it was missing.

## How to test

- [ ] Is this testable with jest or e2e?
- [ ] Does this need an update to the documentation?

## I have confirmed that it is working as expected.

When selecting the `RESTful` `CRUD Operations` module.

Screenshot 2023-11-26 at 13 27 33

When selecting the `GraphQL` `CRUD Operations` module.

Screenshot 2023-11-26 at 13 30 02

### CODE REVIEW

File: packages/create-codes/src/helpers/omit.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  value?: string;
+};
+
+export function omit(
+  dependencies: Record<string, string>,
+  { key, value }: Options
+) {
+  const filteredEntries = Object.entries(dependencies)
+    .filter(([k]) => (key ? ![key].includes(k) : true))
+    .filter(([, v]) => (value ? ![value].includes(v) : true));
```
Comment (ptrkdan) [inline packages/create-codes/src/helpers/omit.ts:12]: [Q] It looks like the `key` and `value` must be an exact match to be filtered out. In the case where the given value is `4.17.21` and the dependency version is `^4.17.21`, should it be ignored?

I was thinking you could normalize the `value` (remove `^` or `~` if it exists) before `.filter()` and just check the version number.

**Review by ptrkdan — COMMENTED** [review]
I have a few comments regarding the `omit` function. Otherwise, LGTM

**Review by ptrkdan — APPROVED** [review]
LGTM! Thank you for making the changes. Perhaps if it becomes necessary, we could refactor a generic utility function in the future.
