### PR TITLE
Copy the selected API's mock for duplication

### LINKED ISSUE #957: Copying the incorrect mock
## Description

It seems that create-codes is not copying the correct mock when duplicating boilerplate.

## Possible Implementation

Correction is needed to copy the appropriate mock according to the selected API.

### PR DESCRIPTION
**Pull request by jinmayamashita**
close #957

## What I did

- [x] Fixed to return mock handlers based on the selected api in the cli
- [x] Fixed the incorrect mock handler path

## How to test

- [ ] Is this testable with jest or e2e?
- [ ] Does this need an update to the documentation?

## Expected behavior

https://github.com/monstar-lab-oss/ml-frontend/assets/9401060/1d88e0c7-9904-4f6e-946a-1f0bbac243e5

### CODE REVIEW

File: packages/create-codes/src/helpers/prompt.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ export type UserInputTests = {
 
 export type UserInput = {
   jsLibrary: JSLibrary;
-  apiSolution: string;
+  apiSolution: "restful" | "graphql";
```
Comment (ptrkdan) [inline packages/create-codes/src/helpers/prompt.ts:14]: Would it be better to create a `type` for `"restful" | "graphql"`?
I think that would make it cleaner.

**Review by ptrkdan — APPROVED** [review]
LGTM! I only have one suggestion regarding type, so I'm going to approve this now.

File: packages/create-codes/src/helpers/prompt.ts (hunk 1 above)
Comment (ptrkdan) [reply packages/create-codes/src/helpers/prompt.ts:14]: Sure, no problem!
